name: whatsapp_clone
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.3
  emoji_picker: ^0.1.0
  shared_preferences: ^0.5.12+4
  camera: ^0.7.0+2
  path_provider: ^1.6.22
  path:
  video_player: ^1.0.1
  socket_io_client: ^0.9.12
  image_picker:
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - images/


  uses-material-design: true

